### PR TITLE
Issue 217: Weaver authentication is making unsafe assumptions on the data and failing out incorrectly.

### LINKED ISSUE #217: Weaver authentication is making unsafe assumptions on the data and failing out incorrectly.
**Describe the bug**
When passed an AUTH_SERVICE_URL that returns an error, the weaver authentication acts as if errors never happen. The data is processed on the expectetation that the payload structure is guaranteed.
This results in an error resulting in a bad state with non-fully resolved user data.
When this happens, the "Obtaining..." messages gets stuck and the user is in a bad login state.

**To Reproduce**
1. Set `AUTH_SERVICE_URL=https://labs.library.tamu.edu/authfix` on a project, such as SAGE.
2. Start docker.
3. Attempt to login.

**Expected behavior**
When an error is received on a login attempt, the error is displayed, the user remains logged out, and there is no stuck "Obtaining...." message.

### PR DESCRIPTION
**Pull request by kaladay**
# Description

When an error occurs either a valid error payload is returned or something else is returned. Do not be opinionated about errors payloads here because the fetchUser should not care at this time.

Preserve the original user role and if it is not defined then set the role to ROLE_ANONYMOUS. Only when the payload has a valid Credentials structure should the session role be deleted and the credentials object be modified.

Having a token when the payload is invalid or the role is anonymous  results in an error message getting stuck. Delete the token in the case that the role is anonymous. After all, the anonymous user should not have a token.

Continue to perform the completion steps needed to resolve the fetchUser request regardless of the payload structure.

Fixes #217

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Ran using verdaccio via localhost against both good and bad auth URL.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: app/services/userService.js [hunk 1]
```diff
@@ -10,10 +10,24 @@ core.service("UserService", function ($q, StorageService, User, WsApi) {
...
+            if (!!body.payload && !!body.payload.Credentials) {
+              delete sessionStorage.role;
+              credentials = angular.fromJson(res.body).payload.Credentials;
+            }
+
+            currentUser.anonymous = !credentials.role || credentials.role === appConfig.anonymousRole ? true : false;
+
+            // Cannot have a token for the anonymous role.
+            if (currentUser.anonymous) {
+              StorageService.delete("token");
```
Comment (ghost) [inline app/services/userService.js:28]: I think this used to not be the case. An anonymous user is a state that can be passed with the token. We may have gotten rid of anonymous use tokens.

File: app/services/userService.js [hunk 2]
```diff
@@ -10,10 +10,24 @@ core.service("UserService", function ($q, StorageService, User, WsApi) {
 
     UserService.fetchUser = function () {
         userEvents.notify('FETCH');
+
         return WsApi.fetch(currentUser.getMapping().instantiate).then(function (res) {
-            delete sessionStorage.role;
-            var credentials = angular.fromJson(res.body).payload.Credentials;
-            currentUser.anonymous = credentials.role === appConfig.anonymousRole ? true : false;
+            var body = !res.body ? {} : angular.fromJson(res.body);
```
Comment (ghost) [inline app/services/userService.js]: @kaladay have you considered `!!res.body` and switching the branches? Shouldn't be applicable here but not entirely positive WsApi fetch proxies' proper HTTP response code and response content type.

File: app/services/userService.js [hunk 3]
```diff
@@ -10,10 +10,24 @@ core.service("UserService", function ($q, StorageService, User, WsApi) {
...
+            var credentials = { role: !currentUser.role ? appConfig.anonymousRole : currentUser.role };
```
Comment (ghost) [inline app/services/userService.js]: I would certainly switch this ternary. `!currentUser.role` may be `!undefined` or even `!null`. If you have checked possible values of role, this can be ignored. However, you can just use `!!currentUser.role ? currentUser.role : appConfig.anonymousRole` without confirming from currentUser.

Comment (ghost) [reply app/services/userService.js]: image

File: app/services/userService.js (hunk 1 above)
Comment (kaladay) [reply app/services/userService.js:28]: Should we treat the token as an existing/another bug?
Authentication is failing but a token is being generated.
The user gets stuck with an invalid token in this case.

File: app/services/userService.js (hunk 2 above)
Comment (kaladay) [reply app/services/userService.js]: I used `!res.body` to avoid the extra operator in `!!res.body` as a good performance practice. But this is Javascript, does the `!res.body` behave differently than `!!!res.body` aside from having 3 exclamations rather than 1?

File: app/services/userService.js (hunk 3 above)
Comment (kaladay) [reply app/services/userService.js]: I want to believe `!null` and `!undefined` resolve to a non-zero value.
But this is Javascript.
Maybe because it is JS I should switch to the double-negative.

Comment (kaladay) [reply app/services/userService.js]: That log shows the desired behavior, the `true` is what I want when using `!test` for cases where test is NULL or test is undefined.

File: app/services/userService.js (hunk 1 above)
Comment (ghost) [reply app/services/userService.js:28]: Yeah, it is likely another bug and should be appropriately cross referenced to Weaver-Webservice-Core.

Comment (kaladay) [reply app/services/userService.js:28]: Should I remove this added "delete token" logic?

File: app/services/userService.js (hunk 2 above)
Comment (ghost) [reply app/services/userService.js]: JavaScript is a pain and not concerned with performance. It is interpreted and possibly can throw away tokens during optimization phases. Have to check the ECMA script specification and each browser implementation. I have been through always using undefined and then just decided to use !! for truthy check against any data type being defined and expected result.

```
!!true === true = true
!!false === false = true
```

Have to check truth table for all possible datatypes and values. Not really much but dont like to bother in JavaScript.

File: app/services/userService.js (hunk 3 above)
Comment (ghost) [reply app/services/userService.js]: Yeah, it may as well be correct in your PR. It just has potential to change elsewhere and break. Not following a specification for response handling is what happened here. Agnostic endpoints were not rigorously planned or thought through. We did not duplicate the entire HTTP standard in WS frames but still ran with it.

File: app/services/userService.js (hunk 2 above)
Comment (kaladay) [reply app/services/userService.js]: I changed the logic after fiddling with the annoyance that is JS boolean logic.

File: app/services/userService.js (hunk 1 above)
Comment (ghost) [reply app/services/userService.js:28]: Nah, I don't think the UIs are utilizing the token for anonymous users. I am pretty sure that was the choice we made. Can confirm through the auth override to the custom user details in SAGE.

https://github.com/TAMULib/SAGE/blob/main/src/main/java/edu/tamu/sage/auth/service/AppUserCredentialsService.java#L17

Keep the delete session storage token if current user is anonymous even if unnecessary.

**Review by ghost — APPROVED** [review]
Code review approved. @rmathew1011 if you could please provide local testing, we can move forward with this update to @wvr/core. We will now need to consider any other changes before rolling out a patch release.

image
